### PR TITLE
[14.0][IMP] fieldservice_sale: Only invoice invoiceable fsm order

### PR DESCRIPTION
**Pull request by ivantodorovich**
Reopen:
- https://github.com/OCA/field-service/pull/1052

---

It looks like we merged https://github.com/OCA/field-service/pull/1053, but not https://github.com/OCA/field-service/pull/1052, which was a direct dependency of the first one.

As a result, we've code calling `_get_invoiceable_fsm_order` (and overriding `_get_invoiceable_fsm_order_domain`), methods that don't exist in the `fieldservice_sale` module, as they were introduced by https://github.com/OCA/field-service/pull/1052

Resulting in:

```
AttributeError: 'sale.order.line' object has no attribute '_get_invoiceable_fsm_order'
```

### CODE REVIEW

**Review by mourad-ehm — APPROVED** [review]

**Review by hparfr — APPROVED** [review]
LGTM
